export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const SET_MOVIES_FILTER = 'SET_MOVIES_FILTER';
export const SET_MOVIES_SORT = 'SET_MOVIES_SORT';
export const CLEAR_MOVIES_DATA = 'CLEAR_MOVIES_DATA';

export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';

export const NEXT_PAGE_REQUEST = 'NEXT_PAGE_REQUEST';
export const NEXT_PAGE_SUCCESS = 'NEXT_PAGE_SUCCESS';
export const NEXT_PAGE_FAIL = 'NEXT_PAGE_FAIL';
