export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const SET_MOVIES_FILTER = 'SET_MOVIES_FILTER';
export const SET_MOVIES_SORT = 'SET_MOVIES_SORT';
export const MOVIE_CLEAR_DATA = 'MOVIE_CLEAR_DATA';

export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';

export const MOVIE_NEXT_PAGE_REQUEST = 'MOVIE_MOVIE_NEXT_PAGE_REQUEST';
export const MOVIE_NEXT_PAGE_SUCCESS = 'MOVIE_NEXT_PAGE_SUCCESS';
export const MOVIE_NEXT_PAGE_FAIL = 'MOVIE_NEXT_PAGE_FAIL';
